### ISSUE TITLE
WIP?

### ISSUE THREAD

**Issue by j2l** [britalmeida/shape_keys_widget#1]
I'd love to see this one coming to life, since the other paid plugin for shapekey is abandoned :cry:

**Comment by britalmeida** [comment]
Hello!
I do still have plans to complete this addon with a workflow for creating visual shapekeys (currently the addon only converts an existing Shape Key Selector V1.0 setup to a rig). As well as plans to place this in the new Blender Extensions system :)

I didn't understand about a paid plugin for shapekey being abandoned? This one? (it's not paid, and it will be "unabandoned" very soon 🤞 )

**Comment by j2l** [comment]
Great news! Can't wait to test it :smile_cat:

**Comment by j2l** [comment]
> I didn't understand about a paid plugin for shapekey being abandoned? This one? (it's not paid, and it will be "unabandoned" very soon 🤞 )

@britalmeida I was speaking about Shape Key Selector v1, stopped at Blender 3.6 in August.

**Comment by britalmeida** [comment]
Ah, clear!
This one is still intended to continue development.

**Comment by j2l** [comment]
@britalmeida please let me know when you develop it so I can test it on my ubuntu desktop!
